tools:
    php_cs_fixer:
        config:
            level: psr2

build:
    nodes:
        analysis:
            tests:
                override:
                    - 'php-scrutinizer-run'
                    -
                        command: 'vendor/bin/phpunit'
                        coverage:
                            file: 'clover.xml'
                            format: 'clover'
