name: PHP Composer

on:
  push:
    branches: ["main"]
  pull_request: ~

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php: "8.2"
            scenario: "symfony6"
          - php: "8.1"
            scenario: "symfony6"
          - php: "8.2"
            scenario: "symfony5"
          - php: "8.1"
            scenario: "symfony5"
          - php: "8.2"
            scenario: "symfony4"
          - php: "8.1"
            scenario: "symfony4"

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP with composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v2

#     - name: Validate composer.json and composer.lock
#       run: composer validate --strict

#     - name: Cache Composer packages
#       id: composer-cache
#       uses: actions/cache@v3
#       with:
#         path: vendor
#         key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#         restore-keys: |
#           ${{ runner.os }}-php-

    - name: Install dependencies
      run: .scenarios.lock/install "${{ matrix.scenario }}" "${{ matrix.dependencies }}"

    - name: PHPStan
      run: vendor/bin/phpstan analyse -c phpstan.neon src/

    - name: atoum
      run: vendor/bin/atoum
